baseURL: "https://arkalim.netlify.app"
languageCode: en-us
title: Home
theme: PaperMod
copyright: "© 2025 All Rights Reserved"


menu:
  main:
    - identifier: about
      name: About
      url: /about
      weight: 10
    - identifier: thoughts
      name: Thoughts
      url: /thoughts
      weight: 20
    - identifier: projects
      name: Projects
      url: /projects
      weight: 30
    # - identifier: experience
    #   name: Experience
    #   url: /experience
    #   weight: 40
    # Search removed
    # - identifier: search
    #   name: Search
    #   url: /search
    #   weight: 50
    - identifier: tags
      name: Tags
      url: /tags
      weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  social:
    twitter: arkalim
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Tim"
    subtitle: Graduate student at UC Irvine studying data science and financial markets.

 
    imageUrl: "home/home.jpg"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: email
      url: "mailto:abdur.rahman.kalim@gmail.com"
    - name: linkedin
      url: "https://www.linkedin.com/in/abdurrahmankalim"
    - name: github
      url: "https://github.com/timavn"

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
